### ISSUE TITLE
docker-compose up 后 azure-openai-proxy 验证正常，chatgpt-web 对话返回 Invalid URL

### ISSUE THREAD

**Issue by peizh** [stulzq/azure-openai-proxy#16]
单独启动 azure-openai-proxy 验证正常，但是用 docker-compose 把两个容器一起启动，chatgpt-web 那边提示网页端对话窗口全是返回Invalid URL，看服务器端 log 提示TypeError [ERR_INVALID_URL]: Invalid URL。但是看 log 里的 URL 又都是对的，proxy 转换也是成功的。
<img width="983" alt="image" src="https://user-images.githubusercontent.com/7479528/232446602-c5213907-31a3-4b7f-800c-451729bf2028.png">
log：

> ubuntu@instance-20210522-1543:~$ sudo docker-compose up
/snap/docker/2746/lib/python3.6/site-packages/paramiko/transport.py:32: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography (40.0) will be the last to support Python 3.6.
  from cryptography.hazmat.backends import default_backend
Creating ubuntu_azure-openai_1 ... done
Creating ubuntu_chatgpt-web_1  ... done
Attaching to ubuntu_azure-openai_1, ubuntu_chatgpt-web_1
azure-openai_1  | 2023/04/17 09:36:26 AzureOpenAIAPIVer:  2023-03-15-preview
azure-openai_1  | 2023/04/17 09:36:26 AzureOpenAIEndpoint:  https://xxxx.openai.azure.com/
azure-openai_1  | 2023/04/17 09:36:26 AzureOpenAIModelMapper:  map[gpt-3.5-turbo:gpt-35-turbo0301-peizh]
azure-openai_1  | 2023/04/17 09:36:26 Server listening at :8080
chatgpt-web_1   |
chatgpt-web_1   | > chatgpt-web-service@1.0.0 prod /app
chatgpt-web_1   | > node ./build/index.mjs
chatgpt-web_1   |
chatgpt-web_1   | Server is running on port 3002
azure-openai_1  | 2023/04/17 09:36:52 proxying request [] /v1/chat/completions -> https://xxxx.openai.azure.com/openai/deployments/gpt-35-turbo0301-xxx/chat/completions?api-version=2023-03-15-preview
azure-openai_1  | [GIN] 2023/04/17 - 09:36:56 | 200 |  3.782634822s |   58.213.197.42 | POST     "/v1/chat/completions"
chatgpt-web_1   | sendMessage (31 tokens) {
chatgpt-web_1   |   max_tokens: 1000,
chatgpt-web_1   |   model: 'gpt-3.5-turbo',
chatgpt-web_1   |   temperature: 0.8,
chatgpt-web_1   |   top_p: 1,
chatgpt-web_1   |   presence_penalty: 1,
chatgpt-web_1   |   messages: [
chatgpt-web_1   |     {
chatgpt-web_1   |       role: 'system',
chatgpt-web_1   |       content: "You are ChatGPT, a large language model trained by OpenAI. Follow the user's instructions carefully. Respond using markdown."
chatgpt-web_1   |     },
chatgpt-web_1   |     { role: 'user', content: 'Hi', name: undefined }
chatgpt-web_1   |   ],
chatgpt-web_1   |   stream: true
chatgpt-web_1   | }
chatgpt-web_1   | TypeError [ERR_INVALID_URL]: Invalid URL
chatgpt-web_1   |     at new NodeError (node:internal/errors:399:5)
chatgpt-web_1   |     at new URL (node:internal/url:560:13)
chatgpt-web_1   |     at new Request (file:///app/node_modules/.pnpm/node-fetch@3.3.0/node_modules/node-fetch/src/request.js:55:16)
chatgpt-web_1   |     at file:///app/node_modules/.pnpm/node-fetch@3.3.0/node_modules/node-fetch/src/index.js:51:19
chatgpt-web_1   |     at new Promise (<anonymous>)
chatgpt-web_1   |     at fetch (file:///app/node_modules/.pnpm/node-fetch@3.3.0/node_modules/node-fetch/src/index.js:49:9)
chatgpt-web_1   |     at options.fetch (file:///app/build/index.mjs:181:14)
chatgpt-web_1   |     at fetchSSE (file:///app/node_modules/.pnpm/chatgpt@5.1.2/node_modules/chatgpt/build/index.js:46:21)
chatgpt-web_1   |     at file:///app/node_modules/.pnpm/chatgpt@5.1.2/node_modules/chatgpt/build/index.js:228:11
chatgpt-web_1   |     at new Promise (<anonymous>) {
chatgpt-web_1   |   input: 'url:8080/v1/chat/completions',
chatgpt-web_1   |   code: 'ERR_INVALID_URL'
chatgpt-web_1   | }

**Comment by peizh** [comment]
好像是因为OPENAI_API_BASE_URL没有加http://

**Comment by peizh** [comment]
果然，我是个傻子，打扰了。
